# Generated by Django 4.2.4 on 2023-09-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_starting_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="account",
            name="starting_balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
