# Generated by Django 4.2.4 on 2023-09-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_current_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="starting_balance",),
    ]
