# Generated by Django 4.2.4 on 2023-09-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_account_starting_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="Balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
