# Generated by Django 4.2.4 on 2023-09-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_balancesnapshot"),
    ]

    operations = [
        migrations.DeleteModel(name="BalanceSnapshot",),
    ]
